<?php

namespace Oip\MszeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    public function findByAny($pattern)
    {
        return $this->getEntityManager()
                ->createQuery('select c from OipMszeBundle:City c where c.name like :pattern or c.district like :pattern or c.slug like :pattern')
                ->setParameter('pattern', '%' . $pattern . '%')
                ->getResult();
    }
}
