<?php

namespace Oip\MszeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistrictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistrictRepository extends EntityRepository
{
        
    public function findDefaultDistrict($city_id)
    {
        return $this->getEntityManager()
                ->createQuery("select d from OipMszeBundle:District d where d.city = :city_id and d.name = ''")
                ->setParameter('city_id', $city_id)
                ->getSingleResult();
    }
    
    public function findOrDef($city_id, $id)
    {
        if ($id != -100) {
            return $this->find($id);
        } else {
            return $this->findDefaultDistrict($city_id);
        }
    }
}
