<?php

namespace Oip\MszeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MassRepository extends EntityRepository
{
    public function findMassesOrderByHour($churchId, $sunday)
    {
        if ($sunday == true) {
            return $this->getEntityManager()
                ->createQuery("select m from OipMszeBundle:Mass m where m.church = :church_id and m.day_sun = 1 order by m.start_time")
                ->setParameter('church_id', $churchId)
                ->getResult();
        }
        else
        {
            return $this->getEntityManager()
                ->createQuery("select m from OipMszeBundle:Mass m where m.church = :church_id and " . 
                        "(m.day_mon = 1 or m.day_tue = 1 or m.day_wed = 1 or " .
                         "m.day_thu = 1 or m.day_fri = 1) order by m.start_time")
                ->setParameter('church_id', $churchId)
                ->getResult();
        }
    }
}
