<?php

namespace Oip\MszeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends EntityRepository
{
    public function getLast()
    {
        $last = $this->getEntityManager()
                ->createQuery('select v from OipMszeBundle:Version v order by v.id')
                ->setMaxResults(1)
                ->getOneOrNullResult();
        return $last;
    }    
    
    public function updateLast($newId)
    {
        $this->getEntityManager()
                ->createQuery('delete from OipMszeBundle:Version v where v.id < :id')
                ->setParameter('id', $newId)
                ->execute();
    }
}
