oip_msze_homepage:
    pattern:  /
    defaults: { _controller: OipMszeBundle:Default:index }
    
show_cities:
    pattern: /show/cities.{_format}
    defaults: { _controller: OipMszeBundle:Show:cities, _format: html }
    requirements:
      _format: html|json|xml
    options:
      expose: true
      
show_city:
    pattern: /show/city/.{_format}
    defaults: { _controller: OipMszeBundle:Show:city, id: -1, _format: html }
    requirements:
      _format: html|json|xml
      id: \d+
    
show_churches:
    pattern: /show/churches/{city_id}
    defaults: { _controller: OipMszeBundle:Show:churches, city_id: -1 }
    
show_church:
    pattern: /show/church/{city_id}/{id}
    defaults: { _controller: OipMszeBundle:Show:church, city_id: -1, id: -1 }
    
show_masses:
    pattern: /show/masses/{church_id}
    defaults: { _controller: OipMszeBundle:Show:masses, church_id: -1 }
    
edit_city:
    pattern: /edit/city/{id}
    defaults: { _controller: OipMszeBundle:Edit:city, id: -1 }
    
    
OipMszeBundle_ajax:
        resource: "@OipMszeBundle/Resources/config/ajax.yml"
        prefix:   /ajax