#oip_msze_homepage:
#    pattern:  /
#    defaults: { _controller: OipMszeBundle:Default:index }

oip_msze_homepage:
    pattern:  /
    defaults: { _controller: OipMszeBundle:EditOrAdd:index, city_id: -1, district_id: -1, church_id: -1 }

          
edit_or_add:
    pattern: /edit_or_add/{city_id}/{district_id}/{church_id}
    defaults: { _controller: OipMszeBundle:EditOrAdd:index, city_id: -1, district_id: -1, church_id: -1 }
    requirements:
      city_id: \d+
      district_id: \d+
      church_id: \d+
    options:
      expose: true
    
show_cities:
    pattern: /show/cities.{_format}
    defaults: { _controller: OipMszeBundle:Show:cities, _format: html }
    requirements:
      _format: html|json|xml
    options:
      expose: true
      
show_city:
    pattern: /show/city/.{_format}
    defaults: { _controller: OipMszeBundle:Show:city, id: -1, _format: html }
    requirements:
      _format: html|json|xml
      id: \d+
    
show_churches:
    pattern: /show/churches/{city_id}
    defaults: { _controller: OipMszeBundle:Show:churches, city_id: -1 }
    
show_church:
    pattern: /show/church/{city_id}/{id}
    defaults: { _controller: OipMszeBundle:Show:church, city_id: -1, id: -1 }
    
show_masses:
    pattern: /show/masses/{church_id}
    defaults: { _controller: OipMszeBundle:Show:masses, church_id: -1 }
    
save_all:
    pattern: /edit_or_add/save_all
    defaults: { _controller: OipMszeBundle:EditOrAdd:save }
    requirements:
      _method: POST
    options:
      expose: true



        
fast_city:
    pattern:  /fast/city/{id}
    defaults: { _controller: "OipMszeBundle:Fast:city", id: -1 }
    options:
      expose: true
      
fast_district:
    pattern:  /fast/district/{id}
    defaults: { _controller: "OipMszeBundle:Fast:district", id: -1 }
    options:
      expose: true

fast_church:
    pattern:  /fast/church/{id}
    defaults: { _controller: "OipMszeBundle:Fast:church", id: -1 }
    options:
      expose: true
      
      